### PR TITLE
Ed25519 crate support

### LINKED ISSUE #4: Agnostic crypto backend
I would like to use this library but not have to rely on `sodiumoxide` for key generation and signing. 

My proposal is to put `KeyPair` behind a feature flag and keep it as a default feature.
Then create a `Signer` trait that can be implemented by a user of this library. `KeyPair` will implement this trait.

I have to fork and do this regardless, but if someone has an idea or desired implementation strategy, please let me know and I will follow that path so the changes can be merged upstream.

### PR DESCRIPTION
**Pull request by trevor-crypto**
Adding support for the `ed25519` crate's traits allows for using any ed25519 backend (libsodium, dalek, etc or even a custom signing implementation).

The default features will continue to use libsodium, which is now behind a feature. There are also a few breaking API changes as well.

This is currently working for me in my usecase (custom signing implementation). Currently don't have much more time to work on refining this, but wanted to share the code regardless.

Closes #4

### CODE REVIEW

**Comment by yellowred** [comment]
@trevor-crypto can you update `ed25519` to  "1.5" please?
@fracek what needs to be done for this PR to be merged?

**Comment by trevor-crypto** [comment]
@yellowred done

**Comment by fracek** [comment]
Looks good, but need status checks to pass.

**Comment by trevor-crypto** [comment]
@fracek woops...Latest commit runs rustfmt

**Comment by fracek** [comment]
Thanks! An sorry for the _slow_ review time.

**Comment by yellowred** [comment]
Nice! Thanks guys.

**Comment by bjorn** [comment]
> The default features will continue to use libsodium, which is now behind a feature. There are also a few breaking API changes as well.

@trevor-crypto An update to the changelog would have been nice, especially regarding the breaking API changes. I'm working towards releasing the current `master` as a 0.6.0 version, and any help with updating the `CHANGELOG.md` regarding this merged PR would be really appreciated!

Edit: I wrote something based on the PR description in 3b6897d235ac7ee1e0a31d6afb0574ea4c86684d.

**Pull request merged**
